dist: trusty
language: minimal
services:
  - docker

git:
  depth: 1

env:
  matrix:
    - PHP_IMG="php-7.2-mongoext-1.3.0-20200327" MONGO_IMG="mongo:3.4" SYMFONY="3.4.*"
    - PHP_IMG="php-7.2-mongoext-1.3.0-20200327" MONGO_IMG="mongo:3.4" SYMFONY="4.3.*"
    - PHP_IMG="php-7.2-mongoext-1.3.0-20200327" MONGO_IMG="mongo:3.4" SYMFONY="4.4.*"
    - PHP_IMG="php-7.2-mongoext-1.5.3-20200327" MONGO_IMG="percona/percona-server-mongodb:4.0"
    - PHP_IMG="php-7.3-mongoext-1.5.3-20200327" MONGO_IMG="mongo:4.0"
    - PHP_IMG="php-7.3-mongoext-1.5.3-20200327" MONGO_IMG="percona/percona-server-mongodb:4.0"

script:
  - make ${TARGET}

notifications:
  on_success: change
  on_failure: change
