dist: trusty
language: minimal
services:
  - docker

git:
  depth: 1

env:
  matrix:
    - TARGET="php-7.2-mongoext-1.3.0"
    - TARGET="php-7.2-mongoext-1.5.3"
    - TARGET="php-7.3-mongoext-1.5.3"
    - TARGET="php-7.4-mongoext-1.6.0"

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

script:
  - make ${TARGET}

notifications:
  on_success: change
  on_failure: change
